include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true

analyzer:
  exclude: [build/**, lib/generated_plugin_registrant.dart, lib/**.freezed.dart, lib/**.g.dart]
  errors:
    invalid_annotation_target: ignore